### ISSUE TITLE
Original CBOR for Redeemer

### ISSUE THREAD

**Issue by euonymos** [utxorpc/spec#132]
I guess the original CBOR for [Redeemer](https://docs.rs/utxorpc-spec/latest/utxorpc_spec/utxorpc/v1alpha/cardano/struct.Redeemer.html) is not available here; it is only JSON representation, which might not be sufficient or be more cumbersome to work with in some cases. It would be nice to have it as it's done for [Datums](https://docs.rs/utxorpc-spec/latest/utxorpc_spec/utxorpc/v1alpha/cardano/struct.Datum.html).

**Comment by Mercurial** [comment]
oh thats a good point!
